---
abstract: 'A MongoDB queue implementation using Mango'
author:
  - 'Ian Kent <iankent@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MangoX-Queue
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mango: 0.43
resources:
  repository: https://github.com/ian-kent/MangoX-Queue
version: 0.14
